### ISSUE TITLE
Deleting user accounts

### ISSUE THREAD

**Issue by xavpinson** [bgo-bioimagerie/platformmanager#114] opened 2019-01-15 08:57 UTC
Hello,
I think the issue has been a bit discussed elsewhere about particular users, but generally is there any way to easily add the possibility to delete accounts?
There are several users with multiple accounts, sometimes with the same email address. In addition to the confusion it creates, I suspect this might cause problems for them to log in.
Thanks.

**Comment by osallou** [comment] 2019-01-15 09:20
easilly? no....
this needs extra development on the software and we are not commited to develop the software, only to host the software.
We are looking to recruit someone for additional devpts, but in the meanwhile...

**Comment by OlivierCollin** [comment] 2019-01-15 10:15
To be more precise, we are looking for the funding. Things seem to be in a good way but "don't count your chickens before they're hatched"...

**Comment by abretaud** [comment] 2019-01-15 16:21
Closing this one as it is a duplicate of #81

**Closed by abretaud** 2019-01-15 16:21 UTC
